eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  #配置端口号
  port: 8099
spring:
  application:
    name: seckill
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql.ipdp.top/competition-product?useUnicode=true&characterEncoding=UTF-8&
    username: root
    password: ipdp@ipdp
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    # spring cache 缓存类型为redis  也可以是其他的实现
    type: redis
  redis:
    host: redis.ipdp.top
    port: 6379
    password: ipdp@ipdp
