eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-provider-control
  datasource:
    url: jdbc:mysql://mysql.ipdp.top/competition-control?useUnicode=true&characterEncoding=UTF-8&
    username: root
    password: ipdp@ipdp
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 1200000

  rabbitmq:
    addresses: 123.206.79.70:5672
    username: ipdp
    password: ipdp
    enabled: true
    max-attempts: 3
    initial-interval: 3000
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000s

server:
  port: 9001
