server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://mysql.ipdp.top/competition-user?useUnicode=true&characterEncoding=UTF-8&
    username: root
    password: ipdp@ipdp
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: 123.206.79.70:5672
    username: ipdp
    password: ipdp
    enabled: true
    max-attempts: 3
    initial-interval: 3000