server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/quartz
    username : fred
    password : fred
    driverClassName : com.mysql.cj.jdbc.Driver
