eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#defaultZone是一个魔术字符串后备值，为任何不表示首选项的客户端提供服务URL（即它是有用的默认值）
spring:
  application:
    name: eureka-provider-user
#指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
server:
  port: 8081